## Load Data

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the csv file.
df=pd.read_csv("https://raw.githubusercontent.com/DanielHughes1580/Project_4_Group_5/main/Data_Cleaned/dummied_data.csv",index_col=0)
df.head()

,Number of Children,Annual Income,Age,Months Employed,Family Members,Months Since Payment,Gender_F,Owns a Car_Y,Owns Property_Y,Income Category_Commercial associate,...,Occupation_Private service staff,Occupation_Realty agents,Occupation_Sales staff,Occupation_Secretaries,Occupation_Security staff,Occupation_Waiters/barmen staff,Status_Major Over,Status_Minor Over,Status_No Loan Taken,Status_Paid
0,0,427500.0,32,4542,2.0,0,False,True,True,False,...,False,False,False,False,False,False,False,False,False,True
1,0,427500.0,32,4542,2.0,1,False,True,True,False,...,False,False,False,False,False,False,False,False,False,True
2,0,427500.0,32,4542,2.0,2,False,True,True,False,...,False,False,False,False,False,False,False,False,False,True
3,0,427500.0,32,4542,2.0,3,False,True,True,False,...,False,False,False,False,False,False,False,False,False,True
4,0,427500.0,32,4542,2.0,4,False,True,True,False,...,False,False,False,False,False,False,False,False,False,True

## Define a function to scale the data, define, compile, fit and evaluate a neural network

In [ ]:
def scale_and_run_nn(df):
  # Create training and target dataframes
  X = df.copy()
  X.drop(["Status_Major Over","Status_Minor Over","Status_No Loan Taken","Status_Paid"], axis=1, inplace=True)
  y = df[["Status_Major Over","Status_Minor Over","Status_No Loan Taken","Status_Paid"]].values

  # Split the preprocessed data into a training and testing dataset
  X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

  # Create a StandardScaler instances
  scaler = StandardScaler()

  # Fit the StandardScaler
  X_scaler = scaler.fit(X_train)

  # Scale the data
  X_train_scaled = X_scaler.transform(X_train)
  X_test_scaled = X_scaler.transform(X_test)


  # Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
  input_features = len(X_train_scaled[0])

  nn = tf.keras.models.Sequential()

  # First hidden layer
  nn.add(tf.keras.layers.Dense(units=50, input_dim=input_features, activation='relu'))

  # Second hidden layer
  nn.add(tf.keras.layers.Dense(units=50, activation='relu'))

  # Output layer
  nn.add(tf.keras.layers.Dense(units=4, activation='sigmoid'))

  # Compile the model
  nn.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

  # Train the model
  fit_model = nn.fit(X_train_scaled,y_train,epochs=20)

  # Evaluate the model using the test data
  model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

  print(f"\nLoss: {model_loss}, Accuracy: {model_accuracy}")

  print(f"\n test input:  {y_test[0:1]}")

  print(f"\n test output: {nn.predict(X_test_scaled[0:1])}")

  return model_loss, model_accuracy, nn

## Optimising by reducing dimensionality

In [ ]:
# There are two columns which have similar data - Income Category_* and Occupation_* - which both give occuption types. Try rmoving Occupation_* from the data
# to see better results are obtained.
red_df = df.drop(columns=['Occupation_Private service staff',"Occupation_Realty agents","Occupation_Sales staff","Occupation_Secretaries","Occupation_Security staff",
                          "Occupation_Waiters/barmen staff",'Occupation_Laborers','Occupation_Low-skill Laborers','Occupation_Managers','Occupation_Medicine staff',
                          'Occupation_Not Specified','Occupation_Pensioner','Occupation_Cooking staff','Occupation_Core staff','Occupation_Drivers','Occupation_HR staff',
                          'Occupation_High skill tech staff','Occupation_IT staff','Occupation_Accountants','Occupation_Cleaning staff'])

# Scale and run the neural net by calling the function
model_loss,model_accuracy, nn = scale_and_run_nn(red_df)

Epoch 1/20
4929/4929 [==============================] - 14s 3ms/step - loss: 0.4423 - accuracy: 0.4948
Epoch 2/20
4929/4929 [==============================] - 12s 2ms/step - loss: 0.4241 - accuracy: 0.5313
Epoch 3/20
4929/4929 [==============================] - 12s 2ms/step - loss: 0.4143 - accuracy: 0.5516
Epoch 4/20
4929/4929 [==============================] - 12s 3ms/step - loss: 0.4078 - accuracy: 0.5638
Epoch 5/20
4929/4929 [==============================] - 12s 2ms/step - loss: 0.4035 - accuracy: 0.5717
Epoch 6/20
4929/4929 [==============================] - 13s 3ms/step - loss: 0.3992 - accuracy: 0.5791
Epoch 7/20
4929/4929 [==============================] - 13s 3ms/step - loss: 0.3961 - accuracy: 0.5851
Epoch 8/20
4929/4929 [==============================] - 12s 3ms/step - loss: 0.3937 - accuracy: 0.5892
Epoch 9/20
4929/4929 [==============================] - 13s 3ms/step - loss: 0.3916 - accuracy: 0.5916
Epoch 10/20
4929/4929 [==============================] - 14s 3ms/step - loss: 0.3897 - accuracy: 0.5949
Epoch 11/20
4929/4929 [==============================] - 12s 2ms/step - loss: 0.3882 - accuracy: 0.5964
Epoch 12/20
4929/4929 [==============================] - 12s 2ms/step - loss: 0.3866 - accuracy: 0.5987
Epoch 13/20
4929/4929 [==============================] - 12s 2ms/step - loss: 0.3854 - accuracy: 0.6007
Epoch 14/20
4929/4929 [==============================] - 11s 2ms/step - loss: 0.3841 - accuracy: 0.6031
Epoch 15/20
4929/4929 [==============================] - 11s 2ms/step - loss: 0.3830 - accuracy: 0.6046
Epoch 16/20
4929/4929 [==============================] - 11s 2ms/step - loss: 0.3818 - accuracy: 0.6072
Epoch 17/20
4929/4929 [==============================] - 12s 2ms/step - loss: 0.3809 - accuracy: 0.6076
Epoch 18/20
4929/4929 [==============================] - 11s 2ms/step - loss: 0.3803 - accuracy: 0.6086
Epoch 19/20
4929/4929 [==============================] - 11s 2ms/step - loss: 0.3794 - accuracy: 0.6101
Epoch 20/20
4929/4929 [==============================] - 12s 2ms/step - loss: 0.3785 - accuracy: 0.6115
1643/1643 - 2s - loss: 0.3827 - accuracy: 0.6049 - 2s/epoch - 1ms/step

Loss: 0.382735937833786, Accuracy: 0.6048957705497742

 test input:  [[False False False  True]]
1/1 [==============================] - 0s 141ms/step

 test output: [[4.7134914e-14 3.6713111e-01 2.6676992e-02 7.0584470e-01]]

In [ ]:
# There are two columns which have similar data - Income Category_* and Occupation_* - which both give occuption types. Now try removing Income Category_* instead from the data
# to see better results are obtained.
red_df = df.drop(columns=["Income Category_Commercial associate","Income Category_Pensioner","Income Category_State servant","Income Category_Working"])

# Scale and run the neural net by calling the function
model_loss,model_accuracy, nn = scale_and_run_nn(red_df)

In [ ]:
# Try dropping the months since payment column
red_df = df.drop(columns=["Months Since Payment"])

# Scale and run the neural net by calling the function
model_loss,model_accuracy, nn = scale_and_run_nn(red_df)