## Load data

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
import pandas as pd
import tensorflow as tf

#  Import and read the csv file.
df=pd.read_csv("https://raw.githubusercontent.com/DanielHughes1580/Project_4_Group_5/main/Data_Cleaned/dummied_data.csv",index_col=0)
df.head()

,Number of Children,Annual Income,Age,Months Employed,Family Members,Months Since Payment,Status,Gender_F,Owns a Car_Y,Owns Property_Y,...,Occupation_Managers,Occupation_Medicine staff,Occupation_Not Specified,Occupation_Pensioner,Occupation_Private service staff,Occupation_Realty agents,Occupation_Sales staff,Occupation_Secretaries,Occupation_Security staff,Occupation_Waiters/barmen staff
0,0,427500.0,32,4542,2.0,0,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
1,0,427500.0,32,4542,2.0,1,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
2,0,427500.0,32,4542,2.0,2,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
3,0,427500.0,32,4542,2.0,3,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
4,0,427500.0,32,4542,2.0,4,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 189095 entries, 0 to 189403
Data columns (total 50 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Number of Children                             189095 non-null  int64
 1   Annual Income                                  189095 non-null  float64
 2   Age                                            189095 non-null  int64
 3   Months Employed                                189095 non-null  int64
 4   Family Members                                 189095 non-null  float64
 5   Months Since Payment                           189095 non-null  int64
 6   Status                                         189095 non-null  object
 7   Gender_F                                       189095 non-null  bool
 8   Owns a Car_Y                                   189095 non-null  bool
 9   Owns Property_Y                                189095 non-null  bool
 10  Income Category_Commercial associate           189095 non-null  bool
 11  Income Category_Pensioner                      189095 non-null  bool
 12  Income Category_State servant                  189095 non-null  bool
 13  Income Category_Working                        189095 non-null  bool
 14  Education Level_Academic degree                189095 non-null  bool
 15  Education Level_Higher education               189095 non-null  bool
 16  Education Level_Incomplete higher              189095 non-null  bool
 17  Education Level_Lower secondary                189095 non-null  bool
 18  Education Level_Secondary / secondary special  189095 non-null  bool
 19  Marital Status_Civil marriage                  189095 non-null  bool
 20  Marital Status_Married                         189095 non-null  bool
 21  Marital Status_Separated                       189095 non-null  bool
 22  Marital Status_Single / not married            189095 non-null  bool
 23  Marital Status_Widow                           189095 non-null  bool
 24  Houseing Type_Co-op apartment                  189095 non-null  bool
 25  Houseing Type_House / apartment                189095 non-null  bool
 26  Houseing Type_Municipal apartment              189095 non-null  bool
 27  Houseing Type_Office apartment                 189095 non-null  bool
 28  Houseing Type_Rented apartment                 189095 non-null  bool
 29  Houseing Type_With parents                     189095 non-null  bool
 30  Occupation_Accountants                         189095 non-null  bool
 31  Occupation_Cleaning staff                      189095 non-null  bool
 32  Occupation_Cooking staff                       189095 non-null  bool
 33  Occupation_Core staff                          189095 non-null  bool
 34  Occupation_Drivers                             189095 non-null  bool
 35  Occupation_HR staff                            189095 non-null  bool
 36  Occupation_High skill tech staff               189095 non-null  bool
 37  Occupation_IT staff                            189095 non-null  bool
 38  Occupation_Laborers                            189095 non-null  bool
 39  Occupation_Low-skill Laborers                  189095 non-null  bool
 40  Occupation_Managers                            189095 non-null  bool
 41  Occupation_Medicine staff                      189095 non-null  bool
 42  Occupation_Not Specified                       189095 non-null  bool
 43  Occupation_Pensioner                           189095 non-null  bool
 44  Occupation_Private service staff               189095 non-null  bool
 45  Occupation_Realty agents                       189095 non-null  bool
 46  Occupation_Sales staff                         189095 non-null  bool
 47  Occupation_Secretaries                         189095 non-null  bool
 48  Occupation_Security staff                      189095 non-null  bool
 49  Occupation_Waiters/barmen staff                189095 non-null  bool
dtypes: bool(43), float64(2), int64(4), object(1)
memory usage: 19.3+ MB

In [ ]:
df.head()

,Number of Children,Annual Income,Age,Months Employed,Family Members,Months Since Payment,Status,Gender_F,Owns a Car_Y,Owns Property_Y,...,Occupation_Managers,Occupation_Medicine staff,Occupation_Not Specified,Occupation_Pensioner,Occupation_Private service staff,Occupation_Realty agents,Occupation_Sales staff,Occupation_Secretaries,Occupation_Security staff,Occupation_Waiters/barmen staff
0,0,427500.0,32,4542,2.0,0,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
1,0,427500.0,32,4542,2.0,1,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
2,0,427500.0,32,4542,2.0,2,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
3,0,427500.0,32,4542,2.0,3,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
4,0,427500.0,32,4542,2.0,4,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False

In [ ]:
# Convert categorical labels to numerical labels
label_encoder = LabelEncoder()
df['status_encoded'] = label_encoder.fit_transform(df['Status'])

# Convert numerical labels to one-hot encoded format
encoded_status = to_categorical(df['status_encoded'])

# Check the encoded status
print(encoded_status)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]

In [ ]:
df.head()

,Number of Children,Annual Income,Age,Months Employed,Family Members,Months Since Payment,Status,Gender_F,Owns a Car_Y,Owns Property_Y,...,Occupation_Medicine staff,Occupation_Not Specified,Occupation_Pensioner,Occupation_Private service staff,Occupation_Realty agents,Occupation_Sales staff,Occupation_Secretaries,Occupation_Security staff,Occupation_Waiters/barmen staff,status_encoded
0,0,427500.0,32,4542,2.0,0,Paid,False,True,True,...,False,True,False,False,False,False,False,False,False,3
1,0,427500.0,32,4542,2.0,1,Paid,False,True,True,...,False,True,False,False,False,False,False,False,False,3
2,0,427500.0,32,4542,2.0,2,Paid,False,True,True,...,False,True,False,False,False,False,False,False,False,3
3,0,427500.0,32,4542,2.0,3,Paid,False,True,True,...,False,True,False,False,False,False,False,False,False,3
4,0,427500.0,32,4542,2.0,4,Paid,False,True,True,...,False,True,False,False,False,False,False,False,False,3

In [ ]:
# Split our preprocessed data into our features and target arrays
# Features
X = df.drop(columns=['Status', 'status_encoded'])
# Target variable
y = encoded_status

In [ ]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
X_train_scaled[0]

array([-0.57388092,  0.31129697, -0.81340695, -0.3076656 , -0.20595609,
       -0.32897776, -1.46446561,  1.24124306, -1.74274175, -0.57374335,
       -0.46747145, -0.30372664,  1.02317769, -0.01354117,  1.67482175,
       -0.20928263, -0.11574984, -1.46387065, -0.29572103,  0.66041463,
       -0.26785538, -0.35657659, -0.21332485, -0.05364769,  0.32010036,
       -0.16677836, -0.07083259, -0.11761247, -0.21548366, -0.17058084,
       -0.10796231, -0.14966163, -0.3425023 , -0.26284686, -0.04858643,
       -0.19372636, -0.01615427, -0.44002125, -0.05114437, -0.31508224,
       -0.18718622,  2.56759363, -0.46747145, -0.10013771, -0.04021595,
       -0.32391475, -0.05936196, -0.12802449, -0.06113032])

In [ ]:
y_train[0]

array([0., 0., 0., 1.], dtype=float32)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(X_train_scaled[0])

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=50, input_dim=input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=50, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=4, activation='sigmoid'))

# Check the structure of the model
nn.summary()

# Compile the model
nn.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=20)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_33 (Dense)            (None, 50)                2500

 dense_34 (Dense)            (None, 50)                2550

 dense_35 (Dense)            (None, 4)                 204

=================================================================
Total params: 5254 (20.52 KB)
Trainable params: 5254 (20.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
4432/4432 [==============================] - 10s 2ms/step - loss: 0.4370 - accuracy: 0.5084
Epoch 2/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.4100 - accuracy: 0.5618
Epoch 3/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3980 - accuracy: 0.5830
Epoch 4/20
4432/4432 [==============================] - 10s 2ms/step - loss: 0.3911 - accuracy: 0.5910
Epoch 5/20
4432/4432 [==============================] - 10s 2ms/step - loss: 0.3864 - accuracy: 0.5976
Epoch 6/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3826 - accuracy: 0.6053
Epoch 7/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3792 - accuracy: 0.6092
Epoch 8/20
4432/4432 [==============================] - 10s 2ms/step - loss: 0.3767 - accuracy: 0.6125
Epoch 9/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3745 - accuracy: 0.6170
Epoch 10/20
4432/4432 [==============================] - 8s 2ms/step - loss: 0.3728 - accuracy: 0.6185
Epoch 11/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3711 - accuracy: 0.6215
Epoch 12/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3693 - accuracy: 0.6236
Epoch 13/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3685 - accuracy: 0.6268
Epoch 14/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3670 - accuracy: 0.6281
Epoch 15/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3659 - accuracy: 0.6300
Epoch 16/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3648 - accuracy: 0.6313
Epoch 17/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3639 - accuracy: 0.6322
Epoch 18/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3630 - accuracy: 0.6346
Epoch 19/20
4432/4432 [==============================] - 11s 3ms/step - loss: 0.3624 - accuracy: 0.6361
Epoch 20/20
4432/4432 [==============================] - 9s 2ms/step - loss: 0.3612 - accuracy: 0.6370
1478/1478 - 2s - loss: 0.3665 - accuracy: 0.6303 - 2s/epoch - 1ms/step
Loss: 0.36654138565063477, Accuracy: 0.6302830576896667

In [ ]:
X_test_scaled[1:2]

array([[-0.57388092, -0.83766258,  0.96078302, -0.54985514, -0.20595609,
         0.23546455,  0.68284294,  1.24124306, -1.74274175, -0.57374335,
        -0.46747145, -0.30372664,  1.02317769, -0.01354117, -0.59707846,
        -0.20928263, -0.11574984,  0.68312046, -0.29572103,  0.66041463,
        -0.26785538, -0.35657659, -0.21332485, -0.05364769,  0.32010036,
        -0.16677836, -0.07083259, -0.11761247, -0.21548366, -0.17058084,
        -0.10796231, -0.14966163, -0.3425023 , -0.26284686, -0.04858643,
        -0.19372636, -0.01615427,  2.27261749, -0.05114437, -0.31508224,
        -0.18718622, -0.38946973, -0.46747145, -0.10013771, -0.04021595,
        -0.32391475, -0.05936196, -0.12802449, -0.06113032]])

In [ ]:
y_test[1:2]

array([[0., 0., 1., 0.]], dtype=float32)

In [ ]:
nn.predict(X_test_scaled[1:2])

WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7c7c28c8a830> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 [==============================] - 0s 61ms/step

array([[3.8672057e-05, 4.0145442e-01, 3.4029272e-01, 2.4563199e-01]],
      dtype=float32)