In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from keras.utils import to_categorical
import pandas as pd
import tensorflow as tf

In [ ]:
# Mount the Google Drive to gain access to functions file
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Access the notebook with my functions
%run '/content/drive/My Drive/Colab Notebooks/Project_4/NN_functions.ipynb'

In [ ]:
#  Import and read the csv file.
df=pd.read_csv("https://media.githubusercontent.com/media/DanielHughes1580/Project_4_Group_5/main/Data_Cleaned/dummied_data_add_clean.csv",index_col=0)
df.head()

,Number of Children,Annual Income,Age,Months Employed,Family Members,Months Since Payment,Status,Gender_F,Owns a Car_Y,Owns Property_Y,...,Occupation_Managers,Occupation_Medicine staff,Occupation_Not Specified,Occupation_Pensioner,Occupation_Private service staff,Occupation_Realty agents,Occupation_Sales staff,Occupation_Secretaries,Occupation_Security staff,Occupation_Waiters/barmen staff
0,0,427500.0,32,4542,2.0,0,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
1,0,427500.0,32,4542,2.0,1,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
2,0,427500.0,32,4542,2.0,2,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
3,0,427500.0,32,4542,2.0,3,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False
4,0,427500.0,32,4542,2.0,4,Paid,False,True,True,...,False,False,True,False,False,False,False,False,False,False

In [ ]:
# Convert categorical labels to numerical labels
label_encoder = LabelEncoder()
df['status_encoded'] = label_encoder.fit_transform(df['Status'])

# Convert numerical labels to one-hot encoded format
encoded_status = to_categorical(df['status_encoded'])

# Split data into features and target
X = df.drop(columns=['Status', 'status_encoded'])  # Features
y = encoded_status  # Target

# Apply PCA
pca = PCA(n_components=10)  # Choose number of components as desired
X_pca = pca.fit_transform(X)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, random_state=78)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
 # Call the model to define, fit and evaluate the neural network model.
 # This model will have 2 hidden layers with 50 neurons in each using the "relu" activation function and will train for 10 epochs
 nn = define_and_fit_nn_model(X_train_scaled, X_test_scaled, y_train, y_test, 2, 50, "relu",10)
 # Look at the prediction for 5 rows
nn_predict(nn,y_test,X_test_scaled)

Input features: 10
Adding layer
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                550

 dense_1 (Dense)             (None, 50)                2550

 dense_2 (Dense)             (None, 3)                 153

=================================================================
Total params: 3253 (12.71 KB)
Trainable params: 3253 (12.71 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/10
18146/18146 [==============================] - 42s 2ms/step - loss: 1.0135 - accuracy: 0.4841
Epoch 2/10
18146/18146 [==============================] - 40s 2ms/step - loss: 0.9923 - accuracy: 0.5002
Epoch 3/10
18146/18146 [==============================] - 40s 2ms/step - loss: 0.9786 - accuracy: 0.5112
Epoch 4/10
18146/18146 [==============================] - 39s 2ms/step - loss: 0.9695 - accuracy: 0.5172
Epoch 5/10
18146/18146 [==============================] - 38s 2ms/step - loss: 0.9627 - accuracy: 0.5226
Epoch 6/10
18146/18146 [==============================] - 38s 2ms/step - loss: 0.9579 - accuracy: 0.5255
Epoch 7/10
18146/18146 [==============================] - 39s 2ms/step - loss: 0.9536 - accuracy: 0.5292
Epoch 8/10
18146/18146 [==============================] - 40s 2ms/step - loss: 0.9506 - accuracy: 0.5318
Epoch 9/10
18146/18146 [==============================] - 40s 2ms/step - loss: 0.9481 - accuracy: 0.5334
Epoch 10/10
18146/18146 [==============================] - 37s 2ms/step - loss: 0.9460 - accuracy: 0.5355
6049/6049 - 9s - loss: 0.9560 - accuracy: 0.5289 - 9s/epoch - 1ms/step

 Test Data Loss: 0.9559792280197144, Test Data Accuracy: 0.5289477109909058

 test input:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
1/1 [==============================] - 0s 90ms/step

 test output:
[[0.27537635 0.09139164 0.633232  ]
 [0.2260988  0.1573051  0.61659604]
 [0.39830232 0.09603278 0.5056649 ]
 [0.380165   0.05882075 0.5610142 ]
 [0.29449102 0.11553103 0.589978  ]]